feat: random update - vue-mastery-card, - drawer info banner and fix issues after rebase
dreamonkey/quasar pull request #136
Opened 2022-03-30 11:05 UTC by n05la3

Opening this as a draft, while waiting for assets.

2022-04-11 16:06 UTC, IlCallo requested changes
Side question: why is VueMastery logo into "homepage" assets folder?

2022-04-11 16:06 UTC, IlCallo commented on docs/src/assets/menu.json
> +    "name": "Docs",
This should be "Docs homepage" when shown into the drawer menu

2022-04-11 16:06 UTC, IlCallo commented on docs/src/assets/menu.json
> +  {
Move this to the end of the array, as this isn't important

2022-04-11 16:23 UTC, IlCallo commented
About VueMastery cards, paddings aren't the correct ones, the button text doesn't have bold weight and VueMastery icon isn't the one from mockups, maybe you need a custom one from Nick?

2022-04-12 09:32 UTC, n05la3 commented
About the vue-mastery-logo being in `homepage`, I have moved it to the root of assets. Can't find any strong reasons for having placed it in that folder.

2022-04-13 17:59 UTC, IlCallo commented
Seems everything is ok now, perfect!

2022-04-13 18:00 UTC, merged