feat(landing): landing page sections
dreamonkey/quasar pull request #3
Opened 2021-10-25 12:23 UTC by n05la3

Landing page with more sections and footer.

2021-10-26 09:37 UTC, IlCallo requested changes

2021-10-26 09:37 UTC, IlCallo commented on docs/public/homepage-icons/QUASAR_icons_astronaut_RGB_EX.svg
> +<?xml version="1.0" encoding="utf-8"?>
When adding custom resources provided by Nick, always rename the files to be human readable
He has a strict naming rules to understand what he's dealing with, but when we use them we don't really need any of those info

Eg. this file sould just be `astronaut.svg`, we already know it's a quasar icon and we don't care it's in RGB format and it's an executive file (EX)

2021-10-26 09:37 UTC, IlCallo commented on docs/public/homepage-icons/QUASAR_icons_astronaut_RGB_EX.svg
> +<?xml version="1.0" encoding="utf-8"?>
In addition, you should optimize resources while adding them

For SVGs we usually go with https://jakearchibald.github.io/svgomg/ , ticking everything which can remove a few bytes without compromising the final result and using precision 1 or 2, the lowest which doesn't distort the resulting image
We do this because SVGs exported by designers tools are usually bloated with random stuff which isn't really needed

For raster images (jpg/png/etc) we use https://kraken.io/web-interface , leaving the default settings on
We do this because raster images given by Nick are usually way bigger than needed for websites

We also have a [loader](https://github.com/dreamonkey/responsive-image-loader) with creates optimized version of raster images for all viewports automatically, but it isn't currently webpack5 compatible and have some performance/caching problems, we need to fix it before using it here

2021-10-26 09:37 UTC, IlCallo commented on docs/src/assets/landing-page/homepage-icons/QUASAR_icons_astronaut_RGB_EX.svg
> +<?xml version="1.0" encoding="utf-8"?>
I think you duplicated these icons both into the public folder and the assets one

2021-10-26 09:37 UTC, IlCallo commented on docs/src/assets/landing-page/landing-page-footer.ts
> +export default [
Always use named exports, IDEs can better find and suggest their imports, and refactoring works better than when using default exports

2021-10-26 09:37 UTC, IlCallo commented on docs/src/layouts/MainLayout.vue
> +    <q-footer class="" style="background-color: #dbe1e5;">
Random empty `class` attribute

2021-10-26 09:37 UTC, IlCallo commented on docs/src/layouts/MainLayout.vue
> +    <q-footer class="" style="background-color: #dbe1e5;">
Never use inline style, the color should be `#d8e1e5` by the way, you mistaken the `8` as a `b`
You better add this color into the landing pages colors and provide bg and text classes as you did for the other ones

2021-10-26 09:37 UTC, IlCallo commented on docs/src/layouts/MainLayout.vue
> +        <div class="help">
Is this class useless or a request for help to me? 👀

2021-10-26 09:37 UTC, IlCallo commented on docs/src/layouts/MainLayout.vue
> +        <div class="help">
The whole div can probably be removed I guess

2021-10-26 09:37 UTC, IlCallo commented on docs/src/layouts/MainLayout.vue
> +            <q-tabs v-model="tabs" align="justify" class="text-grey-7">
`q-tabs` keeps not being the best solution for a toolbar, unless you convince me otherwise
Under the hood, it brings in a lot of tabs related code, complexity and abastractions which you won't actually use

2021-10-26 09:37 UTC, IlCallo commented on docs/src/layouts/MainLayout.vue
> +            <div class="row q-col-gutter-lg q-gutter-y-lg text-size-12 text-capitalize">
`q-gutter` classes and in general Quasar grid helpers should be avoided: they rely on quirks and tricks which may make your life harder later on
Please check out native CSS Grid instead, which solves this exact problem: https://css-tricks.com/snippets/css/complete-guide-grid/

2021-10-26 09:37 UTC, IlCallo commented on docs/src/layouts/MainLayout.vue
> +<style scoped lang="scss">
Avoid the style block if empty

2021-10-26 09:37 UTC, IlCallo commented on docs/src/pages/landing-page/Index.vue
> +    <div class="row justify-end q-pa-md">
As noted by Nick on Zeplin, this should be considered part of the navigation and thus be fixed and be part of the layout, check out the updated mockups

2021-10-26 09:37 UTC, IlCallo commented on docs/src/pages/landing-page/Index.vue
> +          <div style="height: 250px; width: 250px;">
Avoid inline styles, use a class instead

2021-10-26 09:37 UTC, IlCallo commented on docs/src/pages/landing-page/Index.vue
> +          <div class="row items-center justify-center q-py-md">
This should be much easier by using CSS Grid

2021-10-26 09:37 UTC, IlCallo commented on docs/src/pages/landing-page/Index.vue
> +      <div class="text-uppercase text-lp-primary text-size-36 text-weight-bold text-center q-pb-xl">
You should use a margin helper here, not the padding one.
If you don't have the distinction crystal clear, please let me know as it's important you know the difference and when to use which

2021-10-26 09:37 UTC, IlCallo commented on docs/src/pages/landing-page/Index.vue
> +                <q-card class="q-pa-lg text-center column justify-between items-center full-height shadow-bottom-large">
Abstract these cards into a standalone GUI component and reuse it for all 3 cards

2021-10-26 09:37 UTC, IlCallo commented on docs/src/pages/landing-page/Index.vue
> +          class="text-center text-size-24 text-uppercase text-lp-primary text-weight-bold"
These titles should be all the same as styling, same as the quotes
Either you drop the utility classes usage and create new classes for title/subtitle/quote which do the same, or you create a GUI component for each type to group the utility classes and avoid repeating them all the times

2021-10-26 09:37 UTC, IlCallo commented on docs/src/pages/landing-page/Index.vue
> +      <div class="col-9 relative-position" style="padding-bottom: 120px;">
Avoid inline styles

2021-10-26 09:37 UTC, IlCallo commented on docs/src/pages/landing-page/Index.vue
> +    <div class="window-height row justify-center items-end"  style="padding-bottom: 120px;">
Avoid inline styles

2021-10-26 09:37 UTC, IlCallo commented on docs/src/pages/landing-page/Index.vue
> +          style="position: absolute; bottom: 0; right: 0;"
You guessed it at this point... Also, you can get this same effect using `absolute-bottom-right` helper class I guess (can't remember if this is the correct name, but there's a class for this)

2021-10-26 09:37 UTC, IlCallo commented on docs/src/pages/landing-page/Index.vue
> +    <div class="support row justify-center relative-position" style="height: 120vh">
You guessed it already

2021-10-26 09:37 UTC, IlCallo commented on docs/src/pages/landing-page/Index.vue
> +      <div style="width: 50%; position: absolute; left: 0; bottom: 0">
Always the same

2021-10-26 09:37 UTC, IlCallo commented on docs/src/pages/landing-page/Index.vue
> +      <div style="width: 50%; position: absolute; right: 0; top: 0">
Never gonna give you up

2021-10-27 06:57 UTC, n05la3 commented on docs/src/pages/landing-page/Index.vue
> +    <div class="row justify-end q-pa-md">
Oh, okay. I read his reply to my message before making it scrollable. Just read it again, and I realized I misunderstood his second reply in that thread. Will fix it.

2021-10-28 10:05 UTC, n05la3 commented on docs/src/pages/landing-page/Index.vue
> +          <div class="row items-center justify-center q-py-md">
I have simplified the html and classes used, I don't think using grids would be necessary anymore. The logos also have some dark spaces around them (will act as the gutters in this case)

2021-10-28 13:39 UTC, IlCallo requested changes
Pretty good, there's still some stuff to fix around, but many are just stylistic choices we can discuss later on, I only added the ones which confuses me

Can you rename all components thumbnails too? Eg. `Quasar_component_thumbnail_Range.jpg` to `range.jpg` as you can already tell they're thumbnails by their folder name

2021-10-28 13:39 UTC, IlCallo commented on docs/src/pages/landing-page/Index.vue
> +        <template v-for="(src, i) in sponsorLogos" :key="i">
Why not adding `v-for` on the `q-img` directly?

2021-10-28 13:39 UTC, IlCallo commented on docs/src/assets/landing-page/landing-page-footer.ts
> +export { homepageFooterItems, footerToolbar }
Prefer using the export keyword directly, as `export const footerToolbar`

2021-10-28 13:39 UTC, IlCallo commented on docs/src/layouts/MainLayout.vue
> +        <template v-for="({label, to}, i) in footerToolbar" :key="i">
Same as in other places, is there a reason behind not adding the `v-for` on `q-btn`

2021-10-28 14:38 UTC, n05la3 commented on docs/src/layouts/MainLayout.vue
> +        <template v-for="({label, to}, i) in footerToolbar" :key="i">
There's no particular reason, it's just personal preference. I usually prefer that because it sort of tells me immediately everything inside of template is repeated. Also, I sometimes destructure in v-for, if I destructure directly on the element, it just gives the impression of having too many attributes. 

It's really just personal preference. If for this project adding it directly to the element is preferred, let me know and I'll fix it.

2021-10-29 10:11 UTC, IlCallo commented on docs/src/layouts/MainLayout.vue
> +        <template v-for="({label, to}, i) in footerToolbar" :key="i">
We usually go with `v-for` on the element itself, as that's the way suggested from the docs
Not sure if an additional template adds some kind of overhead, surely not much
Let's keep it like this for now, we can possibly fix it later on

2021-10-29 13:49 UTC, IlCallo approved these changes

2021-10-29 13:50 UTC, merged